name = "pages-porfolio"
compatibility_date = "2024-09-19"
pages_build_output_dir = "./assets"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "portfolio-blog-db"
database_id = "9a3055fd-90a1-4abe-bb04-76b412ef385d"